services:
  postgres-db:
    image: postgres:15
    container_name: postgres15
    restart: always
    ports:
      - 5435:5432
    volumes:
      - pg-data:/usr/share/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111
      POSTGRES_DB: project
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432


  es01:
    image: elasticsearch:8.15.2
    depends_on:
      - postgres-db
    container_name: es01
    ports:
      - 9200:9200
    volumes:
      - es-data-es01:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: false

  kibana:
    depends_on:
      - es01
    image: kibana:7.17.24
    ports:
      - 5601:5601
    volumes:
      - kibana:/usr/share/kibana/data
    environment:
      SERVER_NAME: kibana
      server.host: localhost
      ELASTICSEARCH_HOSTS: http://es01:9200

  account:
    depends_on:
      - postgres-db
    build:
      context: ./Account_service
    container_name: account
    ports:
      - 8001:8000
    environment:
      DB_NAME: project
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_HOST: postgres-db
      DB_PORT: 5432
  
  hospital:
    depends_on:
      - postgres-db
    build:
      context: ./Hospital_service
    container_name: hospital
    ports:
      - 8002:8000
    environment:
      DB_NAME: project
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_HOST: postgres-db
      DB_PORT: 5432
    
  timetable:
    depends_on:
      - postgres-db
    build:
      context: ./Timetable_service
    container_name: timetable
    ports:
      - 8003:8000
    environment:
      DB_NAME: project
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_HOST: postgres-db
      DB_PORT: 5432
  
  documents:
    depends_on:
      - postgres-db
    build:
      context: ./Document_service
    container_name: documents
    ports:
      - 8004:8000
    environment:
      DB_NAME: project
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_HOST: postgres-db
      DB_PORT: 5432

volumes:
  pg-data:
  es-data-es01:
  kibana: