# Generated by Django 4.2 on 2024-09-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_user_firstname_user_lastname_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
