# Generated by Django 4.2 on 2024-10-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_firstname_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
